-- Review before running.
-- Generated by scripts/photo-audit.js

update photos set credit_type = 'phot' where photo_id = 1123;
update photos set photographer_slug = 'grossen-charlie', credit_type = 'spry-photo' where photo_id = 1433;
update photos set photographer_slug = '-putch-bentley' where photo_id = 1441;
update photos set photographer_slug = 'kaylaLyn' where photo_id = 1815;
update photos set credit_type = 'jwcrp' where photo_id = 6474;
update photos set credit_type = 'jwcrp' where photo_id = 6477;
update photos set credit_type = 'jwcrp' where photo_id = 6481;
update photos set credit_type = 'jwcrp' where photo_id = 6483;
update photos set credit_type = 'jwcrp' where photo_id = 6484;
update photos set credit_type = 'Post' where photo_id = 24362;
