import Link from 'next/link'
import { notFound } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import styles from '../../special-event.module.css'

export const revalidate=300
const SERIES_IDS=[95,96,98,99,100,101,102,103],MIN_YEAR=1986,MAX_YEAR=2025
const divisionNames:Record<number,string>={95:'Late Model Division',96:'Modified Division',98:'Super Stock Division',99:'Street Stock Division',100:'Midwest Modified Division',101:'Mod Four Division',102:'Pure Stock Division',103:'Hornet Division'}
type ResultRow={id:number;finishing_position:number|null;starting_position:string|null;car_number:string|null;driver_name:string;status:string|null;result_section:string|null}
type RaceRow={id:number;series_id:number|null;race_date:string|null;track_name:string|null;track_slug:string|null;winner_name:string|null;source_url:string|null;SeriesEventResults:ResultRow[]}
function formatDate(value:string|null){if(!value)return'Date not listed';const [y,m,d]=value.split('-');return new Date(Number(y),Number(m)-1,Number(d)).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}
function photoUrl(trackSlug:string,fileName?:string|null,year?:string|null){const base=process.env.NEXT_PUBLIC_SUPABASE_URL;return fileName&&base?`${base}/storage/v1/object/public/media/photos/master/${trackSlug}/${year||'unknown-year'}/${fileName}`:''}

export default async function Wissota100YearPage({params}:{params:Promise<{year:string}>}){
 const {year}=await params;const seasonYear=Number(year);if(!Number.isInteger(seasonYear)||seasonYear<MIN_YEAR||seasonYear>MAX_YEAR)notFound()
 const {data:racesRaw,error}=await supabase.from('SeriesEvents').select(`id,series_id,race_date,track_name,track_slug,winner_name,source_url,SeriesEventResults(id,finishing_position,starting_position,car_number,driver_name,status,result_section)`).in('series_id',SERIES_IDS).gte('race_date',`${seasonYear}-01-01`).lte('race_date',`${seasonYear}-12-31`).order('series_id',{ascending:true}).order('race_date',{ascending:true})
 const races=(racesRaw??[]) as RaceRow[];const cancelled=seasonYear===1987||seasonYear===2020;const previousYear=seasonYear>MIN_YEAR?seasonYear-1:null,nextYear=seasonYear<MAX_YEAR?seasonYear+1:null
 const grouped=new Map<number,RaceRow[]>();for(const race of races){if(!race.series_id)continue;if(!grouped.has(race.series_id))grouped.set(race.series_id,[]);grouped.get(race.series_id)!.push(race)}
 const heroTrackSlug=races.find(r=>r.track_slug)?.track_slug||'cedar-lake-speedway-wi';const {data:photos}=await supabase.from('photos').select('file_name,year').eq('track_slug',heroTrackSlug).neq('credit_type','unknown').or(`year.eq.${seasonYear},year.is.null`).limit(6);const heroSrc=photoUrl(heroTrackSlug,photos?.[0]?.file_name,photos?.[0]?.year)
 const resultRows=races.reduce((sum,r)=>sum+r.SeriesEventResults.length,0)
 return <main className={styles.page}>
  <section className={styles.hero}>{heroSrc?<img src={heroSrc} alt={`${seasonYear} WISSOTA 100`} className={styles.heroImage}/>:null}<div className={styles.heroShade}/><div className={styles.heroInner}>
   <div className={styles.breadcrumbs}><Link href="/">Home</Link><span>›</span><Link href="/events">Special Events</Link><span>›</span><Link href="/events/wissota-100">WISSOTA 100</Link><span>›</span><span>{seasonYear}</span></div>
   <div className={styles.eyebrow}>WISSOTA 100 Edition Archive</div><h1 className={styles.title}>{seasonYear} WISSOTA 100</h1><p className={styles.tagline}>{cancelled?(seasonYear===2020?'COVID Cancellation':'Rained Out'):races.length?`${grouped.size} Championship Division${grouped.size===1?'':'s'}`:'Archive Record Pending'}</p>
   <div className={styles.stats}><Stat label="Edition" value={String(seasonYear)}/><Stat label="Divisions" value={cancelled?'—':String(grouped.size)}/><Stat label="Result Rows" value={cancelled?'—':String(resultRows)}/><Stat label="Archive Status" value={cancelled?'No Event':races.length?'Preserved':'Researching'}/></div>
  </div></section>
  <div className={styles.content}><div className={styles.yearNav}><div>{previousYear?<Link className={styles.yearNavLink} href={`/events/wissota-100/${previousYear}`}>← {previousYear}</Link>:null}</div><Link className={styles.yearNavCenter} href="/events/wissota-100">All Years</Link><div className={styles.yearNavLinkRight}>{nextYear?<Link className={styles.yearNavLink} href={`/events/wissota-100/${nextYear}`}>{nextYear} →</Link>:null}</div></div>
   {cancelled?<section className={styles.section}><div className={styles.sourceCard}><div className={styles.sourceLabel}>{seasonYear} Edition</div><strong>{seasonYear===2020?'The WISSOTA 100 was cancelled during the COVID-19 season.':'The 1987 WISSOTA 100 was rained out.'}</strong><p>No result is fabricated for this edition.</p></div></section>:error?<div className={styles.empty}>Unable to load this WISSOTA 100 year from the Museum database.</div>:races.length?SERIES_IDS.filter(id=>grouped.has(id)).map(id=><DivisionSection key={id} title={divisionNames[id]} races={grouped.get(id)??[]}/>):<div className={styles.empty}>No WISSOTA 100 championship result is currently documented for this year.</div>}
   <div className={styles.footerLinks}><Link href="/events/wissota-100" className={styles.footerLink}>WISSOTA 100<span>Return to event archive →</span></Link><Link href="/tracks" className={styles.footerLink}>Track Archive<span>Explore host venues →</span></Link><Link href="/events" className={styles.footerLink}>Special Events<span>Browse all events →</span></Link></div>
  </div>
 </main>
}
function DivisionSection({title,races}:{title:string;races:RaceRow[]}){return <section className={styles.section}><div className={styles.kicker}>Championship Division</div><div className={styles.sectionHead}><h2>{title}</h2></div>{races.map((race,raceIndex)=>{const feature=race.SeriesEventResults.filter(r=>!['DNQ','DNS'].includes((r.result_section??'').toUpperCase())).sort((a,b)=>(a.finishing_position??9999)-(b.finishing_position??9999));const dnq=race.SeriesEventResults.filter(r=>['DNQ','DNS'].includes((r.result_section??'').toUpperCase())).sort((a,b)=>a.driver_name.localeCompare(b.driver_name));const raceLabel=races.length>1?`Feature ${raceIndex+1}`:'Championship Feature';return <article key={race.id} className={styles.panel}><div className={styles.panelHeader}><h3 className={styles.panelTitle}>{raceLabel} · {formatDate(race.race_date)}</h3><div className={styles.panelMeta}>{race.track_name||'Track not listed'}</div></div><div className={styles.panelBody}><div className={styles.winnerBar}><span>Winner</span><strong>{race.winner_name??feature.find(r=>r.finishing_position===1)?.driver_name??'Not listed'}</strong></div>{feature.length?<div className={styles.resultsScroller}><div className={styles.compactHeader}><span>Pos.</span><span>Car</span><span>Driver</span><span>Start</span><span>Status</span></div>{feature.map(row=><div key={row.id} className={styles.compactRow}><strong>{row.finishing_position??'—'}</strong><span>{row.car_number??'—'}</span><strong>{row.driver_name}</strong><span>{row.starting_position??'—'}</span><span>{row.status??'—'}</span></div>)}</div>:<div className={styles.winnerOnly}>Winner-only record preserved for this division.</div>}{dnq.length?<div className={styles.dnqWrap}><div className={styles.dnqTitle}>Did Not Start / Qualify</div>{dnq.map(row=><span key={row.id} className={styles.dnqChip}>{row.driver_name}{row.car_number?` #${row.car_number}`:''}</span>)}</div>:null}<p className={styles.note}>Only positions preserved by historical sources are shown. Missing finishing positions are not reconstructed. Race of Champions and qualifying-night features remain separate.</p></div></article>})}</section>}
function Stat({label,value}:{label:string;value:string}){return <div className={styles.stat}><div className={styles.statLabel}>{label}</div><div className={styles.statValue}>{value}</div></div>}
